@rem 此脚本表示外部已经打好electron的unpacked files，并且已经复制到我们的FilesToInstall下，我们只需要相应的打包成最终的安装包即可 
@rem 打包脚本名称，如leeqia_simple，对于于SetupScripts目录下的具体文件夹名称
@set project_name=%1
@rem electron中配置的guid，用于指定注册表中的key
@set electron_guid=%2
@rem 软件版本号
@set electron_app_version=%3
@rem 完整的安装包名
@set output_setup_file_name=%4
@rem 是安装到所有用户下，还是安装到当前用户下，all/current
@set shell_all_user_mode=%5
@rem 安装包的启动权限，user/admin
@set install_execution_level=%6
@rem 等待打包文件所在目录名，默认为FilesToInstall
@set file_pack_path=%7
@rem 主程序EXE名称
@set main_exe_name=%8
@rem 是否生成latest.yml，用于electron相关程序的打包 
@set gen_latest=%9
@rem 注册表中安装包位置存储的key值
@set install_location_key=InstallLocation