files:
  - source: /src/browser/src/locale/messages.xlf
    translation: /src/browser/src/locale/messages.%two_letters_code%.xlf
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
