export const genSimpleApiData = () => {
  return {
    apiList: [
      {
        groupId: '',
        groupName: '',
        projectId: '',
        lifecycle: 0,
        name: $localize`Get City Weather Today`,
        uri: '',
        protocol: 0,
        status: 0,
        starred: 0,
        encoding: '',
        isShared: 0,
        tag: '',
        orderNum: 0,
        hashkey: '',
        managerId: '',
        managerName: '',
        updateUserId: '',
        updateUserName: '',
        createUserId: '',
        createUserName: '',
        createTime: '',
        updateTime: '',
        introduction: {
          apiUuid: '',
          noteType: 0,
          noteRaw: '',
          note: '',
          createTime: '',
          updateTime: ''
        },
        relation: {
          apiUuid: '',
          bindAmtApiId: '',
          swaggerId: '',
          fileName: '',
          fileUrl: '',
          fileId: ''
        },
        apiAttrInfo: {
          beforeInject: '',
          afterInject: '',
          authInfo: '',
          requestMethod: 1,
          contentType: 0,
          createTime: '',
          updateTime: ''
        },
        dubboApiAttrInfo: {
          serverHost: '',
          interfaceName: '',
          methodName: '',
          appName: '',
          group: '',
          version: '',
          apiNumber: '',
          createTime: '',
          updateTime: ''
        },
        soapApiAttrInfo: {
          beforeInject: '',
          afterInject: '',
          authInfo: '',
          requestMethod: 0,
          contentType: 0,
          wsdlContent: '',
          testData: '',
          soapOperation: '',
          soapAction: '',
          soapBinding: '',
          soapService: '',
          createTime: '',
          updateTime: ''
        },
        grpcApiAttrInfo: {
          authInfo: '',
          serverHost: '',
          interfaceName: '',
          methodName: '',
          appName: '',
          group: '',
          version: '',
          proto: '',
          apiRequestMetadata: '',
          responseMetadata: '',
          responseTrailingMetadata: '',
          createTime: '',
          updateTime: ''
        },
        requestParams: {
          headerParams: [
            {
              responseUuid: '',
              name: '',
              paramType: 0,
              partType: 0,
              dataType: 0,
              dataTypeValue: '',
              structureId: '',
              structureParamId: '',
              contentType: '',
              isRequired: 0,
              binaryRawData: '',
              description: '',
              orderNo: 0,
              createTime: '',
              updateTime: '',
              paramAttr: {
                minLength: '',
                maxLength: '',
                minValue: {},
                maxValue: {},
                paramLimit: '',
                paramValueList: '',
                paramMock: '',
                attr: '',
                structureIsHide: 0,
                example: '',
                createTime: '',
                updateTime: '',
                dbArr: '',
                paramNote: ''
              },
              childList: []
            }
          ],
          bodyParams: [
            {
              responseUuid: '',
              name: '',
              paramType: 0,
              partType: 0,
              dataType: 0,
              dataTypeValue: '',
              structureId: '',
              structureParamId: '',
              contentType: '',
              isRequired: 0,
              binaryRawData: '',
              description: '',
              orderNo: 0,
              createTime: '',
              updateTime: '',
              paramAttr: {
                minLength: '',
                maxLength: '',
                minValue: {},
                maxValue: {},
                paramLimit: '',
                paramValueList: '',
                paramMock: '',
                attr: '',
                structureIsHide: 0,
                example: '',
                createTime: '',
                updateTime: '',
                dbArr: '',
                paramNote: ''
              },
              childList: []
            }
          ],
          queryParams: [
            {
              responseUuid: '',
              name: '',
              paramType: 0,
              partType: 0,
              dataType: 0,
              dataTypeValue: '',
              structureId: '',
              structureParamId: '',
              contentType: '',
              isRequired: 0,
              binaryRawData: '',
              description: '',
              orderNo: 0,
              createTime: '',
              updateTime: '',
              paramAttr: {
                minLength: '',
                maxLength: '',
                minValue: {},
                maxValue: {},
                paramLimit: '',
                paramValueList: '',
                paramMock: '',
                attr: '',
                structureIsHide: 0,
                example: '',
                createTime: '',
                updateTime: '',
                dbArr: '',
                paramNote: ''
              },
              childList: []
            }
          ],
          restParams: [
            {
              responseUuid: '',
              name: '',
              paramType: 0,
              partType: 0,
              dataType: 0,
              dataTypeValue: '',
              structureId: '',
              structureParamId: '',
              contentType: '',
              isRequired: 0,
              binaryRawData: '',
              description: '',
              orderNo: 0,
              createTime: '',
              updateTime: '',
              paramAttr: {
                minLength: '',
                maxLength: '',
                minValue: {},
                maxValue: {},
                paramLimit: '',
                paramValueList: '',
                paramMock: '',
                attr: '',
                structureIsHide: 0,
                example: '',
                createTime: '',
                updateTime: '',
                dbArr: '',
                paramNote: ''
              },
              childList: []
            }
          ]
        },
        responseList: [
          {
            responseUuid: '',
            apiUuid: '',
            name: '',
            httpCode: '',
            contentType: 0,
            isDefault: 0,
            createTime: '',
            updateTime: '',
            responseParams: {
              headerParams: [
                {
                  responseUuid: '',
                  name: '',
                  paramType: 0,
                  partType: 0,
                  dataType: 0,
                  dataTypeValue: '',
                  structureId: '',
                  structureParamId: '',
                  contentType: '',
                  isRequired: 0,
                  binaryRawData: '',
                  description: '',
                  orderNo: 0,
                  createTime: '',
                  updateTime: '',
                  paramAttr: {
                    minLength: '',
                    maxLength: '',
                    minValue: {},
                    maxValue: {},
                    paramLimit: '',
                    paramValueList: '',
                    paramMock: '',
                    attr: '',
                    structureIsHide: 0,
                    example: '',
                    createTime: '',
                    updateTime: '',
                    dbArr: '',
                    paramNote: ''
                  },
                  childList: []
                }
              ],
              bodyParams: [
                {
                  responseUuid: '',
                  name: '',
                  paramType: 0,
                  partType: 0,
                  dataType: 0,
                  dataTypeValue: '',
                  structureId: '',
                  structureParamId: '',
                  contentType: '',
                  isRequired: 0,
                  binaryRawData: '',
                  description: '',
                  orderNo: 0,
                  createTime: '',
                  updateTime: '',
                  paramAttr: {
                    minLength: '',
                    maxLength: '',
                    minValue: {},
                    maxValue: {},
                    paramLimit: '',
                    paramValueList: '',
                    paramMock: '',
                    attr: '',
                    structureIsHide: 0,
                    example: '',
                    createTime: '',
                    updateTime: '',
                    dbArr: '',
                    paramNote: ''
                  },
                  childList: []
                }
              ],
              queryParams: [
                {
                  responseUuid: '',
                  name: '',
                  paramType: 0,
                  partType: 0,
                  dataType: 0,
                  dataTypeValue: '',
                  structureId: '',
                  structureParamId: '',
                  contentType: '',
                  isRequired: 0,
                  binaryRawData: '',
                  description: '',
                  orderNo: 0,
                  createTime: '',
                  updateTime: '',
                  paramAttr: {
                    minLength: '',
                    maxLength: '',
                    minValue: {},
                    maxValue: {},
                    paramLimit: '',
                    paramValueList: '',
                    paramMock: '',
                    attr: '',
                    structureIsHide: 0,
                    example: '',
                    createTime: '',
                    updateTime: '',
                    dbArr: '',
                    paramNote: ''
                  },
                  childList: []
                }
              ],
              restParams: [
                {
                  responseUuid: '',
                  name: '',
                  paramType: 0,
                  partType: 0,
                  dataType: 0,
                  dataTypeValue: '',
                  structureId: '',
                  structureParamId: '',
                  contentType: '',
                  isRequired: 0,
                  binaryRawData: '',
                  description: '',
                  orderNo: 0,
                  createTime: '',
                  updateTime: '',
                  paramAttr: {
                    minLength: '',
                    maxLength: '',
                    minValue: {},
                    maxValue: {},
                    paramLimit: '',
                    paramValueList: '',
                    paramMock: '',
                    attr: '',
                    structureIsHide: 0,
                    example: '',
                    createTime: '',
                    updateTime: '',
                    dbArr: '',
                    paramNote: ''
                  },
                  childList: []
                }
              ]
            }
          }
        ],
        resultList: [
          {
            id: '',
            name: '',
            httpCode: '',
            httpContentType: '',
            type: 0,
            content: '',
            createTime: '',
            updateTime: ''
          }
        ],
        writeHistory: 0,
        historyInfo: {
          oldId: '',
          updateDesc: '',
          versionId: 0,
          projectVersionId: 0
        }
      }
    ],
    projectUuid: '',
    workSpaceUuid: ''
  };
};
