import { ContentTypeEnum, ProtocolEnum, RequestMethodEnum } from 'eo/workbench/browser/src/app/shared/services/storage/db/enums/api.enum';

export const genSimpleApiData = ({ projectUuid, workSpaceUuid }) => {
  return {
    apiList: [
      {
        groupId: 0,
        groupName: '',
        projectId: 1,
        lifecycle: 0,
        name: $localize`Get City Weather Today`,
        uri: 'http://www.weather.com.cn/data/cityinfo/{cityCode}.html',
        protocol: ProtocolEnum.HTTP,
        status: 0,
        starred: 0,
        encoding: '',
        isShared: 0,
        tag: '',
        orderNum: 0,
        hashkey: '',
        managerId: '',
        managerName: '',
        updateUserId: '',
        updateUserName: '',
        createUserId: '',
        createUserName: '',
        createTime: new Date(),
        updateTime: new Date(),
        introduction: {
          apiUuid: '',
          noteType: 0,
          noteRaw: '',
          note: '',
          createTime: '',
          updateTime: ''
        },
        relation: {
          apiUuid: '',
          bindAmtApiId: '',
          swaggerId: '',
          fileName: '',
          fileUrl: '',
          fileId: ''
        },
        apiAttrInfo: {
          beforeInject: '',
          afterInject: '',
          authInfo: '',
          requestMethod: RequestMethodEnum.GET,
          contentType: ContentTypeEnum.RAW,
          createTime: '',
          updateTime: ''
        },
        dubboApiAttrInfo: {
          serverHost: '',
          interfaceName: '',
          methodName: '',
          appName: '',
          group: '',
          version: '',
          apiNumber: '',
          createTime: '',
          updateTime: ''
        },
        soapApiAttrInfo: {
          beforeInject: '',
          afterInject: '',
          authInfo: '',
          requestMethod: 0,
          contentType: 0,
          wsdlContent: '',
          testData: '',
          soapOperation: '',
          soapAction: '',
          soapBinding: '',
          soapService: '',
          createTime: '',
          updateTime: ''
        },
        grpcApiAttrInfo: {
          authInfo: '',
          serverHost: '',
          interfaceName: '',
          methodName: '',
          appName: '',
          group: '',
          version: '',
          proto: '',
          apiRequestMetadata: '',
          responseMetadata: '',
          responseTrailingMetadata: '',
          createTime: '',
          updateTime: ''
        },
        requestParams: {
          headerParams: [
            {
              responseUuid: '',
              name: '',
              paramType: 0,
              partType: 0,
              dataType: 0,
              dataTypeValue: '',
              structureId: '',
              structureParamId: '',
              contentType: '',
              isRequired: 0,
              binaryRawData: '',
              description: '',
              orderNo: 0,
              createTime: '',
              updateTime: '',
              paramAttr: {
                minLength: '',
                maxLength: '',
                minValue: {},
                maxValue: {},
                paramLimit: '',
                paramValueList: '',
                paramMock: '',
                attr: '',
                structureIsHide: 0,
                example: '',
                createTime: '',
                updateTime: '',
                dbArr: '',
                paramNote: ''
              },
              childList: []
            }
          ],
          bodyParams: [
            {
              responseUuid: '',
              name: '',
              paramType: 0,
              partType: 0,
              dataType: 0,
              dataTypeValue: '',
              structureId: '',
              structureParamId: '',
              contentType: '',
              isRequired: 0,
              binaryRawData: '',
              description: '',
              orderNo: 0,
              createTime: '',
              updateTime: '',
              paramAttr: {
                minLength: '',
                maxLength: '',
                minValue: {},
                maxValue: {},
                paramLimit: '',
                paramValueList: '',
                paramMock: '',
                attr: '',
                structureIsHide: 0,
                example: '',
                createTime: '',
                updateTime: '',
                dbArr: '',
                paramNote: ''
              },
              childList: []
            }
          ],
          queryParams: [
            {
              responseUuid: '',
              name: 'name',
              paramType: 0,
              partType: 0,
              dataType: 0,
              dataTypeValue: '',
              structureId: '',
              structureParamId: '',
              contentType: '',
              isRequired: 0,
              binaryRawData: '',
              description: '',
              orderNo: 0,
              createTime: '',
              updateTime: '',
              paramAttr: {
                minLength: '',
                maxLength: '',
                minValue: {},
                maxValue: {},
                paramLimit: '',
                paramValueList: '',
                paramMock: '',
                attr: '',
                structureIsHide: 0,
                example: 'disease_h5',
                createTime: '',
                updateTime: '',
                dbArr: '',
                paramNote: ''
              },
              childList: []
            }
          ],
          restParams: [
            {
              responseUuid: '',
              name: 'cityCode',
              paramType: 0,
              partType: 0,
              dataType: 0,
              dataTypeValue: '',
              structureId: '',
              structureParamId: '',
              contentType: '',
              isRequired: 0,
              binaryRawData: '',
              description: $localize`City Code : http://www.mca.gov.cn/article/sj/xzqh/2020/20201201.html`,
              orderNo: 0,
              createTime: '',
              updateTime: '',
              paramAttr: {
                minLength: '',
                maxLength: '',
                minValue: {},
                maxValue: {},
                paramLimit: '',
                paramValueList: '',
                paramMock: '',
                attr: '',
                structureIsHide: 0,
                example: '101010100',
                createTime: '',
                updateTime: '',
                dbArr: '',
                paramNote: ''
              },
              childList: []
            }
          ]
        },
        responseList: [
          {
            responseUuid: '',
            apiUuid: '',
            name: '',
            httpCode: '',
            contentType: 0,
            isDefault: 0,
            createTime: '',
            updateTime: '',
            responseParams: {
              headerParams: [
                {
                  responseUuid: '',
                  name: '',
                  paramType: 0,
                  partType: 0,
                  dataType: 0,
                  dataTypeValue: '',
                  structureId: '',
                  structureParamId: '',
                  contentType: '',
                  isRequired: 0,
                  binaryRawData: '',
                  description: '',
                  orderNo: 0,
                  createTime: '',
                  updateTime: '',
                  paramAttr: {
                    minLength: '',
                    maxLength: '',
                    minValue: {},
                    maxValue: {},
                    paramLimit: '',
                    paramValueList: '',
                    paramMock: '',
                    attr: '',
                    structureIsHide: 0,
                    example: '',
                    createTime: '',
                    updateTime: '',
                    dbArr: '',
                    paramNote: ''
                  },
                  childList: []
                }
              ],
              bodyParams: [
                {
                  responseUuid: '',
                  name: 'weatherinfo',
                  paramType: 0,
                  partType: 0,
                  dataType: 13,
                  dataTypeValue: '',
                  structureId: '',
                  structureParamId: '',
                  contentType: '',
                  isRequired: 0,
                  binaryRawData: '',
                  description: '',
                  orderNo: 0,
                  createTime: '',
                  updateTime: '',
                  paramAttr: {
                    minLength: '',
                    maxLength: '',
                    minValue: {},
                    maxValue: {},
                    paramLimit: '',
                    paramValueList: '',
                    paramMock: '',
                    attr: '',
                    structureIsHide: 0,
                    example: '',
                    createTime: '',
                    updateTime: '',
                    dbArr: '',
                    paramNote: ''
                  },
                  childList: [
                    {
                      responseUuid: '',
                      name: 'city',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: '',
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        example: '北京',
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: []
                    },
                    {
                      responseUuid: '',
                      name: 'cityid',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: '',
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        example: '101010100',
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: []
                    },
                    {
                      responseUuid: '',
                      name: 'temp1',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: $localize`minimum temperature`,
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        example: '18℃',
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: []
                    },
                    {
                      responseUuid: '',
                      name: 'temp2',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: $localize`maximun temperature`,
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        example: '31℃',
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: []
                    },
                    {
                      responseUuid: '',
                      name: 'weather',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: '',
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        example: '多云转阴',
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: []
                    },
                    {
                      responseUuid: '',
                      name: 'img1',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: '',
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        example: 'n1.gif',
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: []
                    },
                    {
                      responseUuid: '',
                      name: 'img2',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: '',
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        example: 'd2.gif',
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: []
                    },
                    {
                      responseUuid: '',
                      name: 'ptime',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: '',
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: []
                    }
                  ]
                }
              ],
              queryParams: [
                {
                  responseUuid: '',
                  name: '',
                  paramType: 0,
                  partType: 0,
                  dataType: 0,
                  dataTypeValue: '',
                  structureId: '',
                  structureParamId: '',
                  contentType: '',
                  isRequired: 0,
                  binaryRawData: '',
                  description: '',
                  orderNo: 0,
                  createTime: '',
                  updateTime: '',
                  paramAttr: {
                    minLength: '',
                    maxLength: '',
                    minValue: {},
                    maxValue: {},
                    paramLimit: '',
                    paramValueList: '',
                    paramMock: '',
                    attr: '',
                    structureIsHide: 0,
                    example: '',
                    createTime: '',
                    updateTime: '',
                    dbArr: '',
                    paramNote: ''
                  },
                  childList: []
                }
              ],
              restParams: [
                {
                  responseUuid: '',
                  name: '',
                  paramType: 0,
                  partType: 0,
                  dataType: 0,
                  dataTypeValue: '',
                  structureId: '',
                  structureParamId: '',
                  contentType: '',
                  isRequired: 0,
                  binaryRawData: '',
                  description: '',
                  orderNo: 0,
                  createTime: '',
                  updateTime: '',
                  paramAttr: {
                    minLength: '',
                    maxLength: '',
                    minValue: {},
                    maxValue: {},
                    paramLimit: '',
                    paramValueList: '',
                    paramMock: '',
                    attr: '',
                    structureIsHide: 0,
                    example: '',
                    createTime: '',
                    updateTime: '',
                    dbArr: '',
                    paramNote: ''
                  },
                  childList: []
                }
              ]
            }
          }
        ],
        resultList: [
          {
            id: '',
            name: '',
            httpCode: '',
            httpContentType: '',
            type: 0,
            content: '',
            createTime: '',
            updateTime: ''
          }
        ],
        writeHistory: 0,
        historyInfo: {
          oldId: '',
          updateDesc: '',
          versionId: 0,
          projectVersionId: 0
        }
      },
      {
        groupId: 0,
        groupName: '',
        projectId: 1,
        lifecycle: 0,
        name: $localize`COVID-19 national epidemic`,
        uri: 'https://view.inews.qq.com/g2/getOnsInfo',
        protocol: ProtocolEnum.HTTP,
        status: 0,
        starred: 0,
        encoding: '',
        isShared: 0,
        tag: '',
        orderNum: 0,
        hashkey: '',
        managerId: 0,
        managerName: '',
        updateUserId: '',
        updateUserName: '',
        createUserId: '',
        createUserName: '',
        createTime: '',
        updateTime: '',
        introduction: {
          apiUuid: '',
          noteType: 0,
          noteRaw: '',
          note: '',
          createTime: '',
          updateTime: ''
        },
        relation: {
          apiUuid: '',
          bindAmtApiId: '',
          swaggerId: '',
          fileName: '',
          fileUrl: '',
          fileId: ''
        },
        apiAttrInfo: {
          beforeInject: '',
          afterInject: '',
          authInfo: '',
          requestMethod: 1,
          contentType: 0,
          createTime: '',
          updateTime: ''
        },
        dubboApiAttrInfo: {
          serverHost: '',
          interfaceName: '',
          methodName: '',
          appName: '',
          group: '',
          version: '',
          apiNumber: '',
          createTime: '',
          updateTime: ''
        },
        soapApiAttrInfo: {
          beforeInject: '',
          afterInject: '',
          authInfo: '',
          requestMethod: 0,
          contentType: 0,
          wsdlContent: '',
          testData: '',
          soapOperation: '',
          soapAction: '',
          soapBinding: '',
          soapService: '',
          createTime: '',
          updateTime: ''
        },
        grpcApiAttrInfo: {
          authInfo: '',
          serverHost: '',
          interfaceName: '',
          methodName: '',
          appName: '',
          group: '',
          version: '',
          proto: '',
          apiRequestMetadata: '',
          responseMetadata: '',
          responseTrailingMetadata: '',
          createTime: '',
          updateTime: ''
        },
        requestParams: {
          headerParams: [
            {
              responseUuid: '',
              name: '',
              paramType: 0,
              partType: 0,
              dataType: 0,
              dataTypeValue: '',
              structureId: '',
              structureParamId: '',
              contentType: '',
              isRequired: 0,
              binaryRawData: '',
              description: '',
              orderNo: 0,
              createTime: '',
              updateTime: '',
              paramAttr: {
                minLength: '',
                maxLength: '',
                minValue: {},
                maxValue: {},
                paramLimit: '',
                paramValueList: '',
                paramMock: '',
                attr: '',
                structureIsHide: 0,
                example: '',
                createTime: '',
                updateTime: '',
                dbArr: '',
                paramNote: ''
              },
              childList: []
            }
          ],
          bodyParams: [
            {
              responseUuid: '',
              name: '',
              paramType: 0,
              partType: 0,
              dataType: 0,
              dataTypeValue: '',
              structureId: '',
              structureParamId: '',
              contentType: '',
              isRequired: 0,
              binaryRawData: '',
              description: '',
              orderNo: 0,
              createTime: '',
              updateTime: '',
              paramAttr: {
                minLength: '',
                maxLength: '',
                minValue: {},
                maxValue: {},
                paramLimit: '',
                paramValueList: '',
                paramMock: '',
                attr: '',
                structureIsHide: 0,
                example: '',
                createTime: '',
                updateTime: '',
                dbArr: '',
                paramNote: ''
              },
              childList: []
            }
          ],
          queryParams: [
            {
              responseUuid: '',
              name: '',
              paramType: 0,
              partType: 0,
              dataType: 0,
              dataTypeValue: '',
              structureId: '',
              structureParamId: '',
              contentType: '',
              isRequired: 0,
              binaryRawData: '',
              description: '',
              orderNo: 0,
              createTime: '',
              updateTime: '',
              paramAttr: {
                minLength: '',
                maxLength: '',
                minValue: {},
                maxValue: {},
                paramLimit: '',
                paramValueList: '',
                paramMock: '',
                attr: '',
                structureIsHide: 0,
                example: '',
                createTime: '',
                updateTime: '',
                dbArr: '',
                paramNote: ''
              },
              childList: []
            }
          ],
          restParams: [
            {
              responseUuid: '',
              name: 'cityCode',
              paramType: 0,
              partType: 0,
              dataType: 0,
              dataTypeValue: '',
              structureId: '',
              structureParamId: '',
              contentType: '',
              isRequired: 0,
              binaryRawData: '',
              description: $localize`City Code : http://www.mca.gov.cn/article/sj/xzqh/2020/20201201.html`,
              orderNo: 0,
              createTime: '',
              updateTime: '',
              paramAttr: {
                minLength: '',
                maxLength: '',
                minValue: {},
                maxValue: {},
                paramLimit: '',
                paramValueList: '',
                paramMock: '',
                attr: '',
                structureIsHide: 0,
                example: '101010100',
                createTime: '',
                updateTime: '',
                dbArr: '',
                paramNote: ''
              },
              childList: []
            }
          ]
        },
        responseList: [
          {
            responseUuid: '',
            apiUuid: '',
            name: '',
            httpCode: '',
            contentType: 0,
            isDefault: 0,
            createTime: '',
            updateTime: '',
            responseParams: {
              headerParams: [
                {
                  responseUuid: '',
                  name: '',
                  paramType: 0,
                  partType: 0,
                  dataType: 0,
                  dataTypeValue: '',
                  structureId: '',
                  structureParamId: '',
                  contentType: '',
                  isRequired: 0,
                  binaryRawData: '',
                  description: '',
                  orderNo: 0,
                  createTime: '',
                  updateTime: '',
                  paramAttr: {
                    minLength: '',
                    maxLength: '',
                    minValue: {},
                    maxValue: {},
                    paramLimit: '',
                    paramValueList: '',
                    paramMock: '',
                    attr: '',
                    structureIsHide: 0,
                    example: '',
                    createTime: '',
                    updateTime: '',
                    dbArr: '',
                    paramNote: ''
                  },
                  childList: []
                }
              ],
              bodyParams: [
                {
                  responseUuid: '',
                  name: 'weatherinfo',
                  paramType: 0,
                  partType: 0,
                  dataType: 13,
                  dataTypeValue: '',
                  structureId: '',
                  structureParamId: '',
                  contentType: '',
                  isRequired: 0,
                  binaryRawData: '',
                  description: '',
                  orderNo: 0,
                  createTime: '',
                  updateTime: '',
                  paramAttr: {
                    minLength: '',
                    maxLength: '',
                    minValue: {},
                    maxValue: {},
                    paramLimit: '',
                    paramValueList: '',
                    paramMock: '',
                    attr: '',
                    structureIsHide: 0,
                    example: '',
                    createTime: '',
                    updateTime: '',
                    dbArr: '',
                    paramNote: ''
                  },
                  childList: [
                    {
                      responseUuid: '',
                      name: 'city',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: '',
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        example: '北京',
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: []
                    },
                    {
                      responseUuid: '',
                      name: 'cityid',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: '',
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        example: '101010100',
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: []
                    },
                    {
                      responseUuid: '',
                      name: 'temp1',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: $localize`minimum temperature`,
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        example: '18℃',
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: []
                    },
                    {
                      responseUuid: '',
                      name: 'temp2',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: $localize`maximun temperature`,
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        example: '31℃',
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: []
                    },
                    {
                      responseUuid: '',
                      name: 'weather',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: '',
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        example: '多云转阴',
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: []
                    },
                    {
                      responseUuid: '',
                      name: 'img1',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: '',
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        example: 'n1.gif',
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: []
                    },
                    {
                      responseUuid: '',
                      name: 'img2',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: '',
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        example: 'd2.gif',
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: []
                    },
                    {
                      responseUuid: '',
                      name: 'ptime',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: '',
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: []
                    }
                  ]
                }
              ],
              queryParams: [
                {
                  responseUuid: '',
                  name: '',
                  paramType: 0,
                  partType: 0,
                  dataType: 0,
                  dataTypeValue: '',
                  structureId: '',
                  structureParamId: '',
                  contentType: '',
                  isRequired: 0,
                  binaryRawData: '',
                  description: '',
                  orderNo: 0,
                  createTime: '',
                  updateTime: '',
                  paramAttr: {
                    minLength: '',
                    maxLength: '',
                    minValue: {},
                    maxValue: {},
                    paramLimit: '',
                    paramValueList: '',
                    paramMock: '',
                    attr: '',
                    structureIsHide: 0,
                    example: '',
                    createTime: '',
                    updateTime: '',
                    dbArr: '',
                    paramNote: ''
                  },
                  childList: []
                }
              ],
              restParams: [
                {
                  responseUuid: '',
                  name: '',
                  paramType: 0,
                  partType: 0,
                  dataType: 0,
                  dataTypeValue: '',
                  structureId: '',
                  structureParamId: '',
                  contentType: '',
                  isRequired: 0,
                  binaryRawData: '',
                  description: '',
                  orderNo: 0,
                  createTime: '',
                  updateTime: '',
                  paramAttr: {
                    minLength: '',
                    maxLength: '',
                    minValue: {},
                    maxValue: {},
                    paramLimit: '',
                    paramValueList: '',
                    paramMock: '',
                    attr: '',
                    structureIsHide: 0,
                    example: '',
                    createTime: '',
                    updateTime: '',
                    dbArr: '',
                    paramNote: ''
                  },
                  childList: []
                }
              ]
            }
          }
        ],
        resultList: [
          {
            id: '',
            name: '',
            httpCode: '',
            httpContentType: '',
            type: 0,
            content: '',
            createTime: '',
            updateTime: ''
          }
        ],
        writeHistory: 0,
        historyInfo: {
          oldId: '',
          updateDesc: '',
          versionId: 0,
          projectVersionId: 0
        }
      }
    ],
    projectUuid,
    workSpaceUuid
  };
};
