import { ContentType, Protocol, RequestMethod } from 'eo/workbench/browser/src/app/modules/api-shared/api.model';

export const genSimpleApiData = ({ projectUuid, workSpaceUuid, groupId = 0 }) => {
  return {
    apiList: [
      {
        groupId,
        groupName: '',
        projectId: 1,
        lifecycle: 0,
        name: $localize`Get City Weather Today`,
        uri: 'http://www.weather.com.cn/data/cityinfo/{cityCode}.html',
        protocol: Protocol.HTTP,
        status: 0,
        starred: 0,
        encoding: '',
        isShared: 0,
        tag: '',
        orderNum: 0,
        hashkey: '',
        managerId: '',
        managerName: '',
        updateUserId: '',
        updateUserName: '',
        createUserId: '',
        createUserName: '',
        createTime: new Date(),
        updateTime: new Date(),
        introduction: {
          apiUuid: '',
          noteType: 0,
          noteRaw: '',
          note: '',
          createTime: '',
          updateTime: ''
        },
        relation: {
          apiUuid: '',
          bindAmtApiId: '',
          swaggerId: '',
          fileName: '',
          fileUrl: '',
          fileId: ''
        },
        apiAttrInfo: {
          beforeInject: '',
          afterInject: '',
          authInfo: '',
          requestMethod: RequestMethod.GET,
          contentType: ContentType.RAW,
          createTime: '',
          updateTime: ''
        },
        requestParams: {
          headerParams: [],
          bodyParams: [],
          queryParams: [],
          restParams: [
            {
              responseUuid: '',
              name: 'cityCode',
              paramType: 0,
              partType: 0,
              dataType: 0,
              dataTypeValue: '',
              structureId: '',
              structureParamId: '',
              contentType: '',
              isRequired: 0,
              binaryRawData: '',
              description: $localize`City Code : http://www.mca.gov.cn/article/sj/xzqh/2020/20201201.html`,
              orderNo: 0,
              createTime: '',
              updateTime: '',
              paramAttr: {
                minLength: '',
                maxLength: '',
                minValue: {},
                maxValue: {},
                paramLimit: '',
                paramValueList: JSON.stringify([
                  { value: '110000', description: 'Beijing' },
                  { value: '440000', description: 'Guangdong' }
                ]),
                paramMock: '',
                attr: '',
                structureIsHide: 0,
                example: '101010100',
                createTime: '',
                updateTime: '',
                dbArr: '',
                paramNote: ''
              },
              childList: []
            }
          ]
        },
        responseList: [
          {
            responseUuid: '',
            apiUuid: '',
            name: '',
            httpCode: '',
            contentType: 0,
            isDefault: 0,
            createTime: '',
            updateTime: '',
            responseParams: {
              headerParams: [],
              bodyParams: [
                {
                  responseUuid: '',
                  name: 'weatherinfo',
                  paramType: 0,
                  partType: 0,
                  dataType: 13,
                  dataTypeValue: '',
                  structureId: '',
                  structureParamId: '',
                  contentType: '',
                  isRequired: 1,
                  binaryRawData: '',
                  description: '',
                  orderNo: 0,
                  createTime: '',
                  updateTime: '',
                  paramAttr: {
                    minLength: '',
                    maxLength: '',
                    minValue: {},
                    maxValue: {},
                    paramLimit: '',
                    paramValueList: '',
                    paramMock: '',
                    attr: '',
                    structureIsHide: 0,
                    example: '',
                    createTime: '',
                    updateTime: '',
                    dbArr: '',
                    paramNote: ''
                  },
                  childList: [
                    {
                      responseUuid: '',
                      name: 'city',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: '',
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        example: '北京',
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: []
                    },
                    {
                      responseUuid: '',
                      name: 'cityid',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: '',
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        example: '101010100',
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: []
                    },
                    {
                      responseUuid: '',
                      name: 'temp1',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: $localize`minimum temperature`,
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        example: '18℃',
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: []
                    },
                    {
                      responseUuid: '',
                      name: 'temp2',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: $localize`maximun temperature`,
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        example: '31℃',
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: []
                    },
                    {
                      responseUuid: '',
                      name: 'weather',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: '',
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        example: '多云转阴',
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: []
                    },
                    {
                      responseUuid: '',
                      name: 'img1',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: '',
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        example: 'n1.gif',
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: []
                    },
                    {
                      responseUuid: '',
                      name: 'img2',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: '',
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        example: 'd2.gif',
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: []
                    },
                    {
                      responseUuid: '',
                      name: 'ptime',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: '',
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        example: '18:00',
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: []
                    }
                  ]
                }
              ],
              queryParams: [],
              restParams: []
            }
          }
        ],
        resultList: [
          {
            id: '',
            name: '',
            httpCode: '',
            httpContentType: '',
            type: 0,
            content: '',
            createTime: '',
            updateTime: ''
          }
        ],
        writeHistory: 0,
        historyInfo: {
          oldId: '',
          updateDesc: '',
          versionId: 0,
          projectVersionId: 0
        }
      },
      {
        groupId,
        groupName: '',
        projectId: 1,
        lifecycle: 0,
        name: $localize`COVID-19 national epidemic`,
        uri: 'https://view.inews.qq.com/g2/getOnsInfo',
        protocol: Protocol.HTTP,
        status: 0,
        starred: 0,
        encoding: '',
        isShared: 0,
        tag: '',
        orderNum: 0,
        hashkey: '',
        managerId: 0,
        managerName: '',
        updateUserId: '',
        updateUserName: '',
        createUserId: '',
        createUserName: '',
        createTime: '',
        updateTime: '',
        introduction: {
          apiUuid: '',
          noteType: 0,
          noteRaw: '',
          note: '',
          createTime: '',
          updateTime: ''
        },
        relation: {
          apiUuid: '',
          bindAmtApiId: '',
          swaggerId: '',
          fileName: '',
          fileUrl: '',
          fileId: ''
        },
        apiAttrInfo: {
          beforeInject: '',
          afterInject: '',
          authInfo: '',
          requestMethod: 1,
          contentType: 0,
          createTime: '',
          updateTime: ''
        },
        dubboApiAttrInfo: {
          serverHost: '',
          interfaceName: '',
          methodName: '',
          appName: '',
          group: '',
          version: '',
          apiNumber: '',
          createTime: '',
          updateTime: ''
        },
        soapApiAttrInfo: {
          beforeInject: '',
          afterInject: '',
          authInfo: '',
          requestMethod: 0,
          contentType: 0,
          wsdlContent: '',
          testData: '',
          soapOperation: '',
          soapAction: '',
          soapBinding: '',
          soapService: '',
          createTime: '',
          updateTime: ''
        },
        grpcApiAttrInfo: {
          authInfo: '',
          serverHost: '',
          interfaceName: '',
          methodName: '',
          appName: '',
          group: '',
          version: '',
          proto: '',
          apiRequestMetadata: '',
          responseMetadata: '',
          responseTrailingMetadata: '',
          createTime: '',
          updateTime: ''
        },
        requestParams: {
          headerParams: [],
          bodyParams: [],
          queryParams: [
            {
              responseUuid: '',
              name: 'name',
              paramType: 0,
              partType: 0,
              dataType: 0,
              dataTypeValue: '',
              structureId: '',
              structureParamId: '',
              contentType: '',
              isRequired: 1,
              binaryRawData: '',
              description: '',
              orderNo: 0,
              createTime: '',
              updateTime: '',
              paramAttr: {
                minLength: '',
                maxLength: '',
                minValue: {},
                maxValue: {},
                paramLimit: '',
                paramValueList: '',
                paramMock: '',
                attr: '',
                structureIsHide: 0,
                example: 'disease_h5',
                createTime: '',
                updateTime: '',
                dbArr: '',
                paramNote: ''
              },
              childList: []
            }
          ],
          restParams: []
        },
        responseList: [
          {
            responseUuid: '',
            apiUuid: '',
            name: '',
            httpCode: '',
            contentType: 0,
            isDefault: 0,
            createTime: '',
            updateTime: '',
            responseParams: {
              headerParams: [
                {
                  responseUuid: '',
                  name: 'date',
                  paramType: 0,
                  partType: 0,
                  dataType: 0,
                  dataTypeValue: '',
                  structureId: '',
                  structureParamId: '',
                  contentType: '',
                  isRequired: 1,
                  binaryRawData: '',
                  description: '',
                  orderNo: 0,
                  createTime: '',
                  updateTime: '',
                  paramAttr: {
                    minLength: '',
                    maxLength: '',
                    minValue: {},
                    maxValue: {},
                    paramLimit: '',
                    paramValueList: '',
                    paramMock: '',
                    attr: '',
                    structureIsHide: 0,
                    example: 'Sat, 05 Feb 2022 04:30:44 GMT',
                    createTime: '',
                    updateTime: '',
                    dbArr: '',
                    paramNote: ''
                  },
                  childList: []
                },
                {
                  responseUuid: '',
                  name: 'content-type',
                  paramType: 0,
                  partType: 0,
                  dataType: 0,
                  dataTypeValue: '',
                  structureId: '',
                  structureParamId: '',
                  contentType: '',
                  isRequired: 1,
                  binaryRawData: '',
                  description: '',
                  orderNo: 0,
                  createTime: '',
                  updateTime: '',
                  paramAttr: {
                    minLength: '',
                    maxLength: '',
                    minValue: {},
                    maxValue: {},
                    paramLimit: '',
                    paramValueList: '',
                    paramMock: '',
                    attr: '',
                    structureIsHide: 0,
                    example: 'application/json',
                    createTime: '',
                    updateTime: '',
                    dbArr: '',
                    paramNote: ''
                  },
                  childList: []
                },
                {
                  responseUuid: '',
                  name: 'transfer-encoding',
                  paramType: 0,
                  partType: 0,
                  dataType: 0,
                  dataTypeValue: '',
                  structureId: '',
                  structureParamId: '',
                  contentType: '',
                  isRequired: 1,
                  binaryRawData: '',
                  description: '',
                  orderNo: 0,
                  createTime: '',
                  updateTime: '',
                  paramAttr: {
                    minLength: '',
                    maxLength: '',
                    minValue: {},
                    maxValue: {},
                    paramLimit: '',
                    paramValueList: '',
                    paramMock: '',
                    attr: '',
                    structureIsHide: 0,
                    example: 'chunked',
                    createTime: '',
                    updateTime: '',
                    dbArr: '',
                    paramNote: ''
                  },
                  childList: []
                },
                {
                  responseUuid: '',
                  name: 'connection',
                  paramType: 0,
                  partType: 0,
                  dataType: 0,
                  dataTypeValue: '',
                  structureId: '',
                  structureParamId: '',
                  contentType: '',
                  isRequired: 1,
                  binaryRawData: '',
                  description: '',
                  orderNo: 0,
                  createTime: '',
                  updateTime: '',
                  paramAttr: {
                    minLength: '',
                    maxLength: '',
                    minValue: {},
                    maxValue: {},
                    paramLimit: '',
                    paramValueList: '',
                    paramMock: '',
                    attr: '',
                    structureIsHide: 0,
                    example: 'close',
                    createTime: '',
                    updateTime: '',
                    dbArr: '',
                    paramNote: ''
                  },
                  childList: []
                },
                {
                  responseUuid: '',
                  name: 'server',
                  paramType: 0,
                  partType: 0,
                  dataType: 0,
                  dataTypeValue: '',
                  structureId: '',
                  structureParamId: '',
                  contentType: '',
                  isRequired: 1,
                  binaryRawData: '',
                  description: '',
                  orderNo: 0,
                  createTime: '',
                  updateTime: '',
                  paramAttr: {
                    minLength: '',
                    maxLength: '',
                    minValue: {},
                    maxValue: {},
                    paramLimit: '',
                    paramValueList: '',
                    paramMock: '',
                    attr: '',
                    structureIsHide: 0,
                    example: 'openresty',
                    createTime: '',
                    updateTime: '',
                    dbArr: '',
                    paramNote: ''
                  },
                  childList: []
                },
                {
                  responseUuid: '',
                  name: 'tracecode',
                  paramType: 0,
                  partType: 0,
                  dataType: 0,
                  dataTypeValue: '',
                  structureId: '',
                  structureParamId: '',
                  contentType: '',
                  isRequired: 1,
                  binaryRawData: '',
                  description: '',
                  orderNo: 0,
                  createTime: '',
                  updateTime: '',
                  paramAttr: {
                    minLength: '',
                    maxLength: '',
                    minValue: {},
                    maxValue: {},
                    paramLimit: '',
                    paramValueList: '',
                    paramMock: '',
                    attr: '',
                    structureIsHide: 0,
                    example: '8QMewH9c6JodvyHb5wE=',
                    createTime: '',
                    updateTime: '',
                    dbArr: '',
                    paramNote: ''
                  },
                  childList: []
                },
                {
                  responseUuid: '',
                  name: 'x-client-ip',
                  paramType: 0,
                  partType: 0,
                  dataType: 0,
                  dataTypeValue: '',
                  structureId: '',
                  structureParamId: '',
                  contentType: '',
                  isRequired: 1,
                  binaryRawData: '',
                  description: '',
                  orderNo: 0,
                  createTime: '',
                  updateTime: '',
                  paramAttr: {
                    minLength: '',
                    maxLength: '',
                    minValue: {},
                    maxValue: {},
                    paramLimit: '',
                    paramValueList: '',
                    paramMock: '',
                    attr: '',
                    structureIsHide: 0,
                    example: '120.26.198.150',
                    createTime: '',
                    updateTime: '',
                    dbArr: '',
                    paramNote: ''
                  },
                  childList: []
                },
                {
                  responseUuid: '',
                  name: 'x-server-ip',
                  paramType: 0,
                  partType: 0,
                  dataType: 0,
                  dataTypeValue: '',
                  structureId: '',
                  structureParamId: '',
                  contentType: '',
                  isRequired: 1,
                  binaryRawData: '',
                  description: '',
                  orderNo: 0,
                  createTime: '',
                  updateTime: '',
                  paramAttr: {
                    minLength: '',
                    maxLength: '',
                    minValue: {},
                    maxValue: {},
                    paramLimit: '',
                    paramValueList: '',
                    paramMock: '',
                    attr: '',
                    structureIsHide: 0,
                    example: '58.250.137.40',
                    createTime: '',
                    updateTime: '',
                    dbArr: '',
                    paramNote: ''
                  },
                  childList: []
                }
              ],
              bodyParams: [
                {
                  responseUuid: '',
                  name: 'ret',
                  paramType: 0,
                  partType: 0,
                  dataType: 13,
                  dataTypeValue: '',
                  structureId: '',
                  structureParamId: '',
                  contentType: '',
                  isRequired: 0,
                  binaryRawData: '',
                  description: '',
                  orderNo: 0,
                  createTime: '',
                  updateTime: '',
                  paramAttr: {
                    minLength: '',
                    maxLength: '',
                    minValue: {},
                    maxValue: {},
                    paramLimit: '',
                    paramValueList: '',
                    paramMock: '',
                    attr: '',
                    structureIsHide: 0,
                    example: '',
                    createTime: '',
                    updateTime: '',
                    dbArr: '',
                    paramNote: ''
                  },
                  childList: []
                },
                {
                  responseUuid: '',
                  name: 'data',
                  paramType: 0,
                  partType: 0,
                  dataType: 13,
                  dataTypeValue: '',
                  structureId: '',
                  structureParamId: '',
                  contentType: '',
                  isRequired: 0,
                  binaryRawData: '',
                  description: $localize`The actual parameter is string, in order to show the document expansion display`,
                  orderNo: 0,
                  createTime: '',
                  updateTime: '',
                  paramAttr: {
                    minLength: '',
                    maxLength: '',
                    minValue: {},
                    maxValue: {},
                    paramLimit: '',
                    paramValueList: '',
                    paramMock: '',
                    attr: '',
                    structureIsHide: 0,
                    example: '',
                    createTime: '',
                    updateTime: '',
                    dbArr: '',
                    paramNote: ''
                  },
                  childList: [
                    {
                      responseUuid: '',
                      name: 'areaTree',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: '',
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        example: '',
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: [
                        {
                          responseUuid: '',
                          name: 'name',
                          paramType: 0,
                          partType: 0,
                          dataType: 0,
                          dataTypeValue: '',
                          structureId: '',
                          structureParamId: '',
                          contentType: '',
                          isRequired: 0,
                          binaryRawData: '',
                          description: '',
                          orderNo: 0,
                          createTime: '',
                          updateTime: '',
                          paramAttr: {
                            minLength: '',
                            maxLength: '',
                            minValue: {},
                            maxValue: {},
                            paramLimit: '',
                            paramValueList: '',
                            paramMock: '',
                            attr: '',
                            structureIsHide: 0,
                            example: '中国',
                            createTime: '',
                            updateTime: '',
                            dbArr: '',
                            paramNote: ''
                          },
                          childList: []
                        },
                        {
                          responseUuid: '',
                          name: 'today',
                          paramType: 0,
                          partType: 0,
                          dataType: 0,
                          dataTypeValue: '',
                          structureId: '',
                          structureParamId: '',
                          contentType: '',
                          isRequired: 0,
                          binaryRawData: '',
                          description: '',
                          orderNo: 0,
                          createTime: '',
                          updateTime: '',
                          paramAttr: {
                            minLength: '',
                            maxLength: '',
                            minValue: {},
                            maxValue: {},
                            paramLimit: '',
                            paramValueList: '',
                            paramMock: '',
                            attr: '',
                            structureIsHide: 0,
                            example: '中国',
                            createTime: '',
                            updateTime: '',
                            dbArr: '',
                            paramNote: ''
                          },
                          childList: [
                            {
                              responseUuid: '',
                              name: 'confirm',
                              paramType: 0,
                              partType: 0,
                              dataType: 0,
                              dataTypeValue: '',
                              structureId: '',
                              structureParamId: '',
                              contentType: '',
                              isRequired: 0,
                              binaryRawData: '',
                              description: '',
                              orderNo: 0,
                              createTime: '',
                              updateTime: '',
                              paramAttr: {
                                minLength: '',
                                maxLength: '',
                                minValue: {},
                                maxValue: {},
                                paramLimit: '',
                                paramValueList: '',
                                paramMock: '',
                                attr: '',
                                structureIsHide: 0,
                                example: '321',
                                createTime: '',
                                updateTime: '',
                                dbArr: '',
                                paramNote: ''
                              },
                              childList: []
                            },
                            {
                              responseUuid: '',
                              name: 'isUpdated',
                              paramType: 0,
                              partType: 0,
                              dataType: 0,
                              dataTypeValue: '',
                              structureId: '',
                              structureParamId: '',
                              contentType: '',
                              isRequired: 0,
                              binaryRawData: '',
                              description: '',
                              orderNo: 0,
                              createTime: '',
                              updateTime: '',
                              paramAttr: {
                                minLength: '',
                                maxLength: '',
                                minValue: {},
                                maxValue: {},
                                paramLimit: '',
                                paramValueList: '',
                                paramMock: '',
                                attr: '',
                                structureIsHide: 0,
                                example: 'true',
                                createTime: '',
                                updateTime: '',
                                dbArr: '',
                                paramNote: ''
                              },
                              childList: []
                            }
                          ]
                        },
                        {
                          responseUuid: '',
                          name: 'total',
                          paramType: 0,
                          partType: 0,
                          dataType: 0,
                          dataTypeValue: '',
                          structureId: '',
                          structureParamId: '',
                          contentType: '',
                          isRequired: 0,
                          binaryRawData: '',
                          description: '',
                          orderNo: 0,
                          createTime: '',
                          updateTime: '',
                          paramAttr: {
                            minLength: '',
                            maxLength: '',
                            minValue: {},
                            maxValue: {},
                            paramLimit: '',
                            paramValueList: '',
                            paramMock: '',
                            attr: '',
                            structureIsHide: 0,
                            example: 'true',
                            createTime: '',
                            updateTime: '',
                            dbArr: '',
                            paramNote: ''
                          },
                          childList: [
                            {
                              responseUuid: '',
                              name: 'nowConfirm',
                              paramType: 0,
                              partType: 0,
                              dataType: 0,
                              dataTypeValue: '',
                              structureId: '',
                              structureParamId: '',
                              contentType: '',
                              isRequired: 0,
                              binaryRawData: '',
                              description: '',
                              orderNo: 0,
                              createTime: '',
                              updateTime: '',
                              paramAttr: {
                                minLength: '',
                                maxLength: '',
                                minValue: {},
                                maxValue: {},
                                paramLimit: '',
                                paramValueList: '',
                                paramMock: '',
                                attr: '',
                                structureIsHide: 0,
                                example: '7114',
                                createTime: '',
                                updateTime: '',
                                dbArr: '',
                                paramNote: ''
                              },
                              childList: []
                            },
                            {
                              responseUuid: '',
                              name: 'confirm',
                              paramType: 0,
                              partType: 0,
                              dataType: 0,
                              dataTypeValue: '',
                              structureId: '',
                              structureParamId: '',
                              contentType: '',
                              isRequired: 0,
                              binaryRawData: '',
                              description: '',
                              orderNo: 0,
                              createTime: '',
                              updateTime: '',
                              paramAttr: {
                                minLength: '',
                                maxLength: '',
                                minValue: {},
                                maxValue: {},
                                paramLimit: '',
                                paramValueList: '',
                                paramMock: '',
                                attr: '',
                                structureIsHide: 0,
                                example: '139641',
                                createTime: '',
                                updateTime: '',
                                dbArr: '',
                                paramNote: ''
                              },
                              childList: []
                            },
                            {
                              responseUuid: '',
                              name: 'dead',
                              paramType: 0,
                              partType: 0,
                              dataType: 0,
                              dataTypeValue: '',
                              structureId: '',
                              structureParamId: '',
                              contentType: '',
                              isRequired: 0,
                              binaryRawData: '',
                              description: '',
                              orderNo: 0,
                              createTime: '',
                              updateTime: '',
                              paramAttr: {
                                minLength: '',
                                maxLength: '',
                                minValue: {},
                                maxValue: {},
                                paramLimit: '',
                                paramValueList: '',
                                paramMock: '',
                                attr: '',
                                structureIsHide: 0,
                                example: '5700',
                                createTime: '',
                                updateTime: '',
                                dbArr: '',
                                paramNote: ''
                              },
                              childList: []
                            },
                            {
                              responseUuid: '',
                              name: 'showRate',
                              paramType: 0,
                              partType: 0,
                              dataType: 0,
                              dataTypeValue: '',
                              structureId: '',
                              structureParamId: '',
                              contentType: '',
                              isRequired: 0,
                              binaryRawData: '',
                              description: '',
                              orderNo: 0,
                              createTime: '',
                              updateTime: '',
                              paramAttr: {
                                minLength: '',
                                maxLength: '',
                                minValue: {},
                                maxValue: {},
                                paramLimit: '',
                                paramValueList: '',
                                paramMock: '',
                                attr: '',
                                structureIsHide: 0,
                                example: '5700',
                                createTime: '',
                                updateTime: '',
                                dbArr: '',
                                paramNote: ''
                              },
                              childList: []
                            },
                            {
                              responseUuid: '',
                              name: 'heal',
                              paramType: 0,
                              partType: 0,
                              dataType: 0,
                              dataTypeValue: '',
                              structureId: '',
                              structureParamId: '',
                              contentType: '',
                              isRequired: 0,
                              binaryRawData: '',
                              description: '',
                              orderNo: 0,
                              createTime: '',
                              updateTime: '',
                              paramAttr: {
                                minLength: '',
                                maxLength: '',
                                minValue: {},
                                maxValue: {},
                                paramLimit: '',
                                paramValueList: '',
                                paramMock: '',
                                attr: '',
                                structureIsHide: 0,
                                example: '126827',
                                createTime: '',
                                updateTime: '',
                                dbArr: '',
                                paramNote: ''
                              },
                              childList: []
                            },
                            {
                              responseUuid: '',
                              name: 'showHeal',
                              paramType: 0,
                              partType: 0,
                              dataType: 0,
                              dataTypeValue: '',
                              structureId: '',
                              structureParamId: '',
                              contentType: '',
                              isRequired: 0,
                              binaryRawData: '',
                              description: '',
                              orderNo: 0,
                              createTime: '',
                              updateTime: '',
                              paramAttr: {
                                minLength: '',
                                maxLength: '',
                                minValue: {},
                                maxValue: {},
                                paramLimit: '',
                                paramValueList: '',
                                paramMock: '',
                                attr: '',
                                structureIsHide: 0,
                                example: 'true',
                                createTime: '',
                                updateTime: '',
                                dbArr: '',
                                paramNote: ''
                              },
                              childList: []
                            },
                            {
                              responseUuid: '',
                              name: 'wzz',
                              paramType: 0,
                              partType: 0,
                              dataType: 0,
                              dataTypeValue: '',
                              structureId: '',
                              structureParamId: '',
                              contentType: '',
                              isRequired: 0,
                              binaryRawData: '',
                              description: '',
                              orderNo: 0,
                              createTime: '',
                              updateTime: '',
                              paramAttr: {
                                minLength: '',
                                maxLength: '',
                                minValue: {},
                                maxValue: {},
                                paramLimit: '',
                                paramValueList: '',
                                paramMock: '',
                                attr: '',
                                structureIsHide: 0,
                                example: '',
                                createTime: '',
                                updateTime: '',
                                dbArr: '',
                                paramNote: ''
                              },
                              childList: []
                            }
                          ]
                        },
                        {
                          responseUuid: '',
                          name: 'children',
                          paramType: 0,
                          partType: 0,
                          dataType: 0,
                          dataTypeValue: '',
                          structureId: '',
                          structureParamId: '',
                          contentType: '',
                          isRequired: 0,
                          binaryRawData: '',
                          description: '',
                          orderNo: 0,
                          createTime: '',
                          updateTime: '',
                          paramAttr: {
                            minLength: '',
                            maxLength: '',
                            minValue: {},
                            maxValue: {},
                            paramLimit: '',
                            paramValueList: '',
                            paramMock: '',
                            attr: '',
                            structureIsHide: 0,
                            example: '',
                            createTime: '',
                            updateTime: '',
                            dbArr: '',
                            paramNote: ''
                          },
                          childList: []
                        }
                      ]
                    },

                    {
                      responseUuid: '',
                      name: 'chinaTotal',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: '',
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        example: '',
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: []
                    },
                    {
                      responseUuid: '',
                      name: 'chinaAdd',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: '',
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        example: '',
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: []
                    },
                    {
                      responseUuid: '',
                      name: 'showAddSwitch',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: '',
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        example: '',
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: []
                    },
                    {
                      responseUuid: '',
                      name: 'lastUpdateTime',
                      paramType: 0,
                      partType: 0,
                      dataType: 0,
                      dataTypeValue: '',
                      structureId: '',
                      structureParamId: '',
                      contentType: '',
                      isRequired: 0,
                      binaryRawData: '',
                      description: '',
                      orderNo: 0,
                      createTime: '',
                      updateTime: '',
                      paramAttr: {
                        minLength: '',
                        maxLength: '',
                        minValue: {},
                        maxValue: {},
                        paramLimit: '',
                        paramValueList: '',
                        paramMock: '',
                        attr: '',
                        structureIsHide: 0,
                        example: '2022-02-05 11:52:51',
                        createTime: '',
                        updateTime: '',
                        dbArr: '',
                        paramNote: ''
                      },
                      childList: []
                    }
                  ]
                }
              ],
              queryParams: [],
              restParams: []
            }
          }
        ],
        resultList: [
          {
            id: '',
            name: '',
            httpCode: '',
            httpContentType: '',
            type: 0,
            content: '',
            createTime: '',
            updateTime: ''
          }
        ],
        writeHistory: 0,
        historyInfo: {
          oldId: '',
          updateDesc: '',
          versionId: 0,
          projectVersionId: 0
        }
      }
    ],
    projectUuid,
    workSpaceUuid
  };
};
