name: 'Bug Report'
description: Create a report to help project improve
body:
  - type: markdown
    attributes:
      value: |
        Before opening an issue, we recommend:
        * Use English to communicate.
        * Search for duplicates of [Issues](https://github.com/Postcatlab/postcat/issues) and [Discussions](https://github.com/Postcatlab/postcat/discussions) unresolved.
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is..
      placeholder: |
        What is the issue with the current behavior?
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Share your environment details. Reports without proper environment details will likely be closed.
      placeholder: |
        - Postcat Version [e.g. 1.7.0]
        - OS: [e.g. Darwin arm64 21.5.0]
    validations:
      required: true
