# release.yml

# workflow 's name
name: Build electron App for Win

on:
  push:
    tags:
      - 'v*.*.*'

# Workflow's jobs
jobs:
  # job's id
  release:
    # job's name
    name: build and release electron app
    # the type of machine to run the job on
    runs-on: ${{ matrix.os }}

    # Platforms to build on/for
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      # step1: check out repository
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      # step2: install & build app for win
      - run: yarn install --frozen-lockfile
      - run: yarn global add @angular/cli
      - run: yarn release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
