/*
 * DO NOT EDIT!
 * This file was automatically generated by ark.
 */

const { chromium } = require('playwright')

;(async () => {
  const wait = async (ms) => new Promise((resolve) => setTimeout(resolve, ms))

  const browser = await chromium.launch({
    headless: false
  })
  const context = await browser.newContext()
  // * 打开新标签页
  const page = await context.newPage()

  // * 跳转至该地址: localhost:4200
  await page.goto('localhost:4200')

  // * 测试完成，关闭浏览器

  await context.close()
  await browser.close()
})()
