name: develop Merge main

on:
  push:
    branches:
      - build/windows
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Using REST API pre-master2 Merge pre-master
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "content-type: application/json" \
          -H "authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          https://github.com/Postcatlab/github-action/merges \
          -d '{"base":"test/merge","head":"build/windows"}'
