name: Release

# github release event list: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release

on:
  release:
    types: [published]

jobs:
  release:
    name: Qi niu published
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3.0.0

      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16'

      - name: Release for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          npm i -g qiniu@6.x
          echo "${{ secrets.QINIU_ENV_JS }}" > ./scripts/qiniu_env.js
          node scripts/publish.js
