name: Merge main branch to build/windows
on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge main -> build/windows
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: build/windows
          github_token: ${{ github.token }}
