name: TestRelease

on:
  push:
    branches: [test/windows_sign]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
      - name: Connect to VPN
        uses: 'kota65535/github-openvpn-connect-action@v2'
        with:
          config_file: .github/workflows/client.ovpn
      - name: Build something
        run: |
          npm install ssh2
          ping -c 4 10.8.0.130
          node scripts/deployWindows.js
